# Generated by Django 4.0.2 on 2022-04-13 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Reivew',
        ),
    ]
